Fix remotes discovery when using ssh.github.com
microsoft/vscode-pull-request-github pull request #2742
Opened 2021-05-21 04:47 UTC by msgongora

Fixes #1656
As explained [here](https://github.com/microsoft/vscode-pull-request-github/issues/1656#issuecomment-845246423), when ssh.github.com is used, the module assume this hostname is a GitHubServer instead of GItHub and because of that the module build a wrong URI to query the API.
I'm not a nodejs developer but I hope this change could inspire a better implementation or a maintainer who understand the architecture.

2021-05-28 08:11 UTC, hmc-cs-mdrissi commented
If you compare directly with ssh.github.com then this may work with normal github but not fix the issue for github enterprise where some other path is used.

2021-06-16 07:42 UTC, msgongora commented
@hmc-cs-mdrissi the issue this PR is addressing is #1656 which doesn't have anything to do with github enterprise. I explained [here](https://github.com/microsoft/vscode-pull-request-github/issues/1656#issuecomment-845240683) the possible causes.

2021-07-25 09:12 UTC, hmc-cs-mdrissi commented
github enterprise has a similar issue of ssh not working. The relevance is github enterprise domain names are different. instead of github.com and ssh.github.com it's something like github.custom_domain and ssh.github.custom_domain. So the comparison directly with 'github.com' looks like it'll fix the issue for common github usage but leave ssh github not working for enterprise. I'm not familiar enough with the code to understand why it directly compares with github.com in the first place.

2021-09-02 21:22 UTC, msgongora commented
Closed it by mistake

2021-10-13 14:04 UTC, leodido commented
Also, hasn't Github enterprise support been discontinued?

Or at least, this is what I understand by reading:

https://github.com/microsoft/vscode-pull-request-github/wiki#2-is-github-enterprise-supported

In this case, +1 to this PR for me

2021-10-14 17:58 UTC, msgongora commented
I haven't got any recommendation from the owner of this extension to get this approved/merged but in the meantime, for those being impacted by the issue this PR is fixing: you could package your own extension from this PR, installing from a VSIX, I have been using it in my daily basis for months with this fix.
```console
# installing tooling(not needed if you already have node/yarn) 
brew install nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
nvm install v12.22.1
nvm use v12.22.1
npm install --global yarn

# 2. cloning the repo, patching code and building extension
git clone https://github.com/microsoft/vscode-pull-request-github.git
cd vscode-pull-request-github/
gh pr checkout 2742   #github cli

MYSUFFIX=msgongora    #you can change this to whatever you like
VERSION=$(sed -nE 's/.*\"version\": \"(.*)\",/\1/p' package.json)
sed -iE -r "s/(github-)insiders/\1$MYSUFFIX/" scripts/prepare-nightly-build.js

yarn
node ./scripts/prepare-nightly-build.js -v $VERSION -i vscode-pull-request-github-$MYSUFFIX -n "GitHub Pull Request $MYSUFFIX Build" -d "$MYSUFFIX Build GitHub Pull Request extension" -p GitHub
mv ./package.insiders.json ./package.json
mv ./src/constants.insiders.ts ./src/constants.ts

yarn global add vsce
vsce package
# testing first from insider
code-insiders --install-extension vscode-pull-request-github-$MYSUFFIX-$VERSION.vsix

#if everything work as you would expect, uninstall official one from you stable vscode installation and install vsix
code --uninstall-extension GitHub.vscode-pull-request-github
code --install-extension vscode-pull-request-github-$MYSUFFIX-$VERSION.vsix
```

2021-11-16 02:20 UTC, iptvlati requested changes
https://cineraw.yzx/iptvlatinacr.m3u8
[](url)

2021-11-24 15:45 UTC, alexr00 commented
Thank for the PR and for your patience on this issue! I would expect the issue that this PR addresses to be resolved by f837b766033fd48ef28b16abcfc3f85303992f90, which will be available in the next release.

2021-11-24 15:45 UTC, closed without merging