UI fixes for the checks section
microsoft/vscode-pull-request-github pull request #4059
Opened 2022-10-14 19:37 UTC by Thomas1664

- Make show/hide an actual button
- properly andle long names for checks

2022-10-14 23:24 UTC, Thomas1664 commented
Note that I reported the smaller ✔ on the wrapping check name as #4064

2022-10-14 23:52 UTC, daviddossett requested changes

2022-10-14 23:52 UTC, daviddossett commented on webviews/components/merge.tsx
> +					<button className='secondary' onClick={toggleDetails} style={{ padding: '0 5px', marginLeft: 'auto' }}>
Let's avoid inline styles. What would be great here would be to extract the styles out of the header's new button group into something like `.small-button` so we can reuse them across both areas.

2022-10-17 17:51 UTC, alexr00 approved these changes
Looks good to me, thank you for the PR! Will merge after @daviddossett has also signed off.

2022-10-17 18:52 UTC, daviddossett approved these changes
Looks good!

2022-10-17 18:56 UTC, merged