add keybindings to acc help content
microsoft/vscode-pull-request-github pull request #5977
Opened 2024-04-29 15:37 UTC by meganrogge

2024-04-29 15:43 UTC, chrmarti approved these changes

2024-04-29 15:55 UTC, alexr00 requested changes
Thanks for adding these!

2024-04-29 15:55 UTC, alexr00 commented on package.nls.json
>  		"comment": [
The create command is just `pr.create`.

```suggestion
		"message":"Helpful commands include:\n-GitHub Pull Requests: Refresh Pull Requests List<keybinding:pr.refreshList>\n-GitHub Pull Requests: Focus on Issues View<keybinding:issues:github.focus> \n-GitHub Pull Requests: Focus on Pull Requests View<keybinding:pr:github.focus>\n-GitHub Issues: Copy GitHub Permalink<keybinding:issue.copyGithubPermalink>\n-GitHub Issues: Create an Issue<keybinding:issue.createIssueFromFile>\n-GitHub Pull Requests: Create Pull Request<keybinding:pr.create>",
		"comment": [
```

2024-04-29 17:32 UTC, Tyriar approved these changes

2024-04-30 07:40 UTC, alexr00 commented
Disabled auto merge as I'm planning to release out of `main` and so don't want any May items in there yet.

2024-05-03 07:46 UTC, merged